compressor_type: bm25
language: en
use_query: True
token_length_zh: 128
token_length_en: 150
topN: 5
compressed_length: 512
graph:
  edge_type: coor/semantic/m3e
  window_size: 50
  use_tfidf: false
  use_position: false